feat: implement i18n for error messages #923 #924
geostyler/geostyler-sld-parser pull request #928
Opened 2024-06-19 08:47 UTC by ocruze

2024-06-19 09:23 UTC, KaiVolland reviewed
Nice job @ocruze. I added some notes to limitations the typings would introduce.

2024-06-19 09:23 UTC, KaiVolland commented on src/SldStyleParser.ts
> +  translations?: Partial<SldStyleParserTranslations>;
If you use `Partial` you usually loose some informations and typings get less strict. Maybe you can just make the Locale keys optional too.

2024-06-19 09:23 UTC, KaiVolland commented on src/SldStyleParser.ts
> +export type SldStyleParserTranslations = Record<Locale, Partial<SldStyleParserTranslationKeys>>;
As every key in the the `SldStyleParserTranslationKeys` is optional you should not need to use `Partial`.

2024-06-19 09:23 UTC, KaiVolland commented on src/SldStyleParser.ts
> +  translate(key: keyof SldStyleParserTranslationKeys, params?: any): string{
```suggestion
  translate(key: keyof SldStyleParserTranslationKeys, params?: any): string {
```

2024-06-19 09:23 UTC, KaiVolland commented on src/SldStyleParser.ts
> +type Locale = (typeof SUPPORTED_LOCALES)[number];
I'm not sure if typing this is much of benefit as you can't provide a custom translation (e.g. spanish with 'es') without changing the source code. So I'd suggest to remove these typings:

```suggestion
```

2024-06-19 09:23 UTC, KaiVolland commented on src/SldStyleParser.ts
> +export type SldStyleParserTranslations = Record<Locale, Partial<SldStyleParserTranslationKeys>>;
See comment above regarding limiting translations.

```suggestion
export type SldStyleParserTranslations = Record<string, Partial<SldStyleParserTranslationKeys>>;
```

2024-06-19 11:12 UTC, slafayIGN commented on src/SldStyleParser.ts
> +      'Lecture de MarkSymbolizer échoué. Le WellKnownName {{wellKnownName}} n\'est pas supporté.',
Échec de lecture du symbole de type MarkSymbolizer. Le WellKnownName...

2024-06-19 11:13 UTC, slafayIGN commented on src/SldStyleParser.ts
> +    symbolizerKindParseFailed: 'Lecture de SymbolizerKind {{sldSymbolizerName}} à partir de SldRule échoué.',
Échec de lecture du type de symbole {{sldSymbolizerName}} à partir de SldRule.

2024-06-19 11:13 UTC, slafayIGN commented on src/SldStyleParser.ts
> +    colorMapEntriesParseFailedColorUndefined: 'Lecture de ColorMapEntries échoué. color n\'est pas défini.',
Échec...

2024-06-19 11:17 UTC, slafayIGN requested changes
Some other translations suggestions in french

2024-06-19 11:17 UTC, slafayIGN commented on src/SldStyleParser.ts
> +      'Lecture de ContrastEnhancement échoué. Histogram et Normalize sont mutuellement exclusifs.',
Échec de lecture des propriétés de contraste ContrastEnhancement. Histogram....

2024-06-19 11:17 UTC, slafayIGN commented on src/SldStyleParser.ts
> +      'Lecture de ChannelSelection échoué. RGB et Grayscale sont mutuellement exclusifs.',
Échec de lecture de la sélection de canaux ChannelSelection....

2024-06-19 11:17 UTC, slafayIGN commented on src/SldStyleParser.ts
> +      'Lecture de ChannelSelection échoué. Les canaux Rouge, Vert et Bleu doivent être définis.',
Pareil

2024-06-21 11:24 UTC, jansule approved these changes
Very nice!

2024-06-21 11:24 UTC, merged

2024-06-21 11:58 UTC, jansule commented
:tada: This PR is included in version 5.4.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/geostyler-sld-parser/v/5.4.0)
- [GitHub release](https://github.com/geostyler/geostyler-sld-parser/releases/tag/v5.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: